require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'MyResume' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-appearance', :path => '../node_modules/react-native-appearance'

  pod 'RNTextGradientView', :path => '../node_modules/react-native-text-gradient'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'RNGoogleSignin', :path => '../node_modules/@react-native-community/google-signin'

  target 'MyResumeTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'MyResume-tvOS' do
  # Pods for MyResume-tvOS

  target 'MyResume-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
